## Introduction to NumPy

> NumPy (Numeric Python) is an extension to the Python programming language, adding support for large, multi-dimensional (mostly numerical) arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays.

In [1]:
# importing all required modules
import numpy as np

In [4]:
list1 = [100, 200, 400, 500, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, 200, 400, 500, 300] 5 <class 'list'>
[100 200 400 500 300] 5 <class 'numpy.ndarray'> int32


In [3]:
tuple1 = [100, 200, 400, 500, 300]
print (tuple1, len(tuple1), type(tuple1))
arr1 = np.array(tuple1)
print (arr1, len(arr1), type(arr1))

[100, 200, 400, 500, 300] 5 <class 'list'>
[100 200 400 500 300] 5 <class 'numpy.ndarray'>


In [6]:
list1 = [100, "200", 400, 500, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, '200', 400, 500, 300] 5 <class 'list'>
['100' '200' '400' '500' '300'] 5 <class 'numpy.ndarray'> <U11


In [7]:
list1 = [100, 200.5, 400, 500, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, 200.5, 400, 500, 300] 5 <class 'list'>
[100.  200.5 400.  500.  300. ] 5 <class 'numpy.ndarray'> float64


In [8]:
list1 = [100, 200, True, 400, 500, False, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, 200, True, 400, 500, False, 300] 7 <class 'list'>
[100 200   1 400 500   0 300] 7 <class 'numpy.ndarray'> int32


In [9]:
list1 = [100, "200", 400.5, True, 500, 300, False]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, '200', 400.5, True, 500, 300, False] 7 <class 'list'>
['100' '200' '400.5' 'True' '500' '300' 'False'] 7 <class 'numpy.ndarray'> <U32


In [10]:
var1 = range(10)
print (var1, type(var1), len(var1))
print (list(var1))

range(0, 10) <class 'range'> 10
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
arr1 = np.arange(10)
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(2, 10)
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(2, 10, 2)
print (arr1, len(arr1), type(arr1))

[0 1 2 3 4 5 6 7 8 9] 10 <class 'numpy.ndarray'>
[2 3 4 5 6 7 8 9] 8 <class 'numpy.ndarray'>
[2 4 6 8] 4 <class 'numpy.ndarray'>


In [25]:
arr1 = np.arange(10, dtype='float')
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(10).astype(float)
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(10).astype(str)
print (arr1, len(arr1), type(arr1))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 10 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 10 <class 'numpy.ndarray'>
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9'] 10 <class 'numpy.ndarray'>


In [29]:
arr1 = np.arange(10, dtype='float')
print (arr1, len(arr1), type(arr1))
print (arr1.dtype) # data type
print (len(arr1))  # first dimension
print (arr1.shape) # dimension
print (arr1.size)  # data count
print (arr1.ndim)  # number of dimension

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 10 <class 'numpy.ndarray'>
float64
10
(10,)
10
1


In [27]:
var1 = (10)
print (var1, type(var1))
var1 = (10,)   # singleton representation of a tuple
print (var1, type(var1))

10 <class 'int'>
(10,) <class 'tuple'>


In [32]:
arr2 = np.array([[100, 200, 300, 400], [111, 222, 333, 444]])
print (arr2, type(arr2))
print (len(arr2))
print (arr2.ndim)
print (arr2.dtype)
print (arr2.shape)
print (arr2.size)

[[100 200 300 400]
 [111 222 333 444]] <class 'numpy.ndarray'>
2
2
int32
(2, 4)
8


In [42]:
arr2 = np.arange(10)
print (arr2)
arr2 = np.arange(10).astype(float)
print (arr2)
arr2 = np.arange(10).astype(float).reshape(2, 5)
print (arr2)
arr2 = np.arange(10).reshape(2, 5).astype(float)
print (arr2, arr2.shape, arr2.size)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] (2, 5) 10


In [45]:
# creation of special arrays
arr1 = np.zeros(10)
print (arr1, type(arr1))
arr1 = np.zeros(10).astype(int)
print (arr1, type(arr1))
arr1 = np.zeros(10, dtype = int)
print (arr1, type(arr1))
arr1 = arr1 + 5
print (arr1, type(arr1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[5 5 5 5 5 5 5 5 5 5] <class 'numpy.ndarray'>


In [46]:
arr1 = np.ones(10)
print (arr1, type(arr1))
arr1 = np.ones(10).astype(int)
print (arr1, type(arr1))
arr1 = np.ones(10, dtype = int)
print (arr1, type(arr1))
arr1 = arr1 + 5
print (arr1, type(arr1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1] <class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1] <class 'numpy.ndarray'>
[6 6 6 6 6 6 6 6 6 6] <class 'numpy.ndarray'>
