## Introduction to NumPy

> NumPy (Numeric Python) is an extension to the Python programming language, adding support for large, multi-dimensional (mostly numerical) arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays.

In [1]:
# importing all required modules
import numpy as np

In [4]:
list1 = [100, 200, 400, 500, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, 200, 400, 500, 300] 5 <class 'list'>
[100 200 400 500 300] 5 <class 'numpy.ndarray'> int32


In [3]:
tuple1 = [100, 200, 400, 500, 300]
print (tuple1, len(tuple1), type(tuple1))
arr1 = np.array(tuple1)
print (arr1, len(arr1), type(arr1))

[100, 200, 400, 500, 300] 5 <class 'list'>
[100 200 400 500 300] 5 <class 'numpy.ndarray'>


In [6]:
list1 = [100, "200", 400, 500, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, '200', 400, 500, 300] 5 <class 'list'>
['100' '200' '400' '500' '300'] 5 <class 'numpy.ndarray'> <U11


In [7]:
list1 = [100, 200.5, 400, 500, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, 200.5, 400, 500, 300] 5 <class 'list'>
[100.  200.5 400.  500.  300. ] 5 <class 'numpy.ndarray'> float64


In [8]:
list1 = [100, 200, True, 400, 500, False, 300]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, 200, True, 400, 500, False, 300] 7 <class 'list'>
[100 200   1 400 500   0 300] 7 <class 'numpy.ndarray'> int32


In [9]:
list1 = [100, "200", 400.5, True, 500, 300, False]
print (list1, len(list1), type(list1))
arr1 = np.array(list1)
print (arr1, len(arr1), type(arr1), arr1.dtype)

[100, '200', 400.5, True, 500, 300, False] 7 <class 'list'>
['100' '200' '400.5' 'True' '500' '300' 'False'] 7 <class 'numpy.ndarray'> <U32


In [10]:
var1 = range(10)
print (var1, type(var1), len(var1))
print (list(var1))

range(0, 10) <class 'range'> 10
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
arr1 = np.arange(10)
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(2, 10)
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(2, 10, 2)
print (arr1, len(arr1), type(arr1))

[0 1 2 3 4 5 6 7 8 9] 10 <class 'numpy.ndarray'>
[2 3 4 5 6 7 8 9] 8 <class 'numpy.ndarray'>
[2 4 6 8] 4 <class 'numpy.ndarray'>


In [25]:
arr1 = np.arange(10, dtype='float')
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(10).astype(float)
print (arr1, len(arr1), type(arr1))
arr1 = np.arange(10).astype(str)
print (arr1, len(arr1), type(arr1))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 10 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 10 <class 'numpy.ndarray'>
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9'] 10 <class 'numpy.ndarray'>


In [29]:
arr1 = np.arange(10, dtype='float')
print (arr1, len(arr1), type(arr1))
print (arr1.dtype) # data type
print (len(arr1))  # first dimension
print (arr1.shape) # dimension
print (arr1.size)  # data count
print (arr1.ndim)  # number of dimension

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 10 <class 'numpy.ndarray'>
float64
10
(10,)
10
1


In [27]:
var1 = (10)
print (var1, type(var1))
var1 = (10,)   # singleton representation of a tuple
print (var1, type(var1))

10 <class 'int'>
(10,) <class 'tuple'>


In [32]:
arr2 = np.array([[100, 200, 300, 400], [111, 222, 333, 444]])
print (arr2, type(arr2))
print (len(arr2))
print (arr2.ndim)
print (arr2.dtype)
print (arr2.shape)
print (arr2.size)

[[100 200 300 400]
 [111 222 333 444]] <class 'numpy.ndarray'>
2
2
int32
(2, 4)
8


In [42]:
arr2 = np.arange(10)
print (arr2)
arr2 = np.arange(10).astype(float)
print (arr2)
arr2 = np.arange(10).astype(float).reshape(2, 5)
print (arr2)
arr2 = np.arange(10).reshape(2, 5).astype(float)
print (arr2, arr2.shape, arr2.size)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] (2, 5) 10


In [45]:
# creation of special arrays
arr1 = np.zeros(10)
print (arr1, type(arr1))
arr1 = np.zeros(10).astype(int)
print (arr1, type(arr1))
arr1 = np.zeros(10, dtype = int)
print (arr1, type(arr1))
arr1 = arr1 + 5
print (arr1, type(arr1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>
[5 5 5 5 5 5 5 5 5 5] <class 'numpy.ndarray'>


In [46]:
arr1 = np.ones(10)
print (arr1, type(arr1))
arr1 = np.ones(10).astype(int)
print (arr1, type(arr1))
arr1 = np.ones(10, dtype = int)
print (arr1, type(arr1))
arr1 = arr1 + 5
print (arr1, type(arr1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1] <class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1] <class 'numpy.ndarray'>
[6 6 6 6 6 6 6 6 6 6] <class 'numpy.ndarray'>


In [48]:
arr1 = np.array([100, 200, 300, 400])
arr2 = np.array([11, 22, 33, 44])
print (arr1, type(arr1))
print (arr2, type(arr2))
print (arr1 + arr2)
print (arr1 - arr2)
print (arr1 * arr2)
print (arr1 / arr2)
print (arr1 % arr2)

[100 200 300 400] <class 'numpy.ndarray'>
[11 22 33 44] <class 'numpy.ndarray'>
[111 222 333 444]
[ 89 178 267 356]
[ 1100  4400  9900 17600]
[9.09090909 9.09090909 9.09090909 9.09090909]
[1 2 3 4]


In [50]:
print (np.zeros(10).reshape(2, 5))
print (np.ones(10).reshape(2, 5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
arr1 = np.linspace(0, 10, 11)
print (arr1, type(arr1))
arr1 = np.linspace(0, 1, 5)
print (arr1, type(arr1))
arr1 = np.linspace(0, 1, 6)
print (arr1, type(arr1))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] <class 'numpy.ndarray'>
[0.   0.25 0.5  0.75 1.  ] <class 'numpy.ndarray'>
[0.  0.2 0.4 0.6 0.8 1. ] <class 'numpy.ndarray'>


In [61]:
arr1 = np.logspace(0, 3, 4)
print (arr1)
arr1 = np.logspace(0, 4, 5)
print (arr1)
arr1 = np.logspace(0, 3, 4, base = 2)
print (arr1)
arr1 = np.logspace(0, 4, 5, base = 2)
print (arr1)
arr1 = np.logspace(0, 4, 5, base = 2).astype(int)
print (arr1)
arr1 = np.logspace(0, 4, 5, base = 2, dtype = int)
print (arr1)

[   1.   10.  100. 1000.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[1. 2. 4. 8.]
[ 1.  2.  4.  8. 16.]
[ 1  2  4  8 16]
[ 1  2  4  8 16]


In [62]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

### Indexing and Slicing

In [72]:
# left to right -> 0    1    2    3    4    5    6    7  
arr1 = np.array([200, 300, 500, 600, 400, 900, 700, 800])
# left to right ->-8   -7   -6   -5   -4   -3   -2   -1
print (arr1, type(arr1), len(arr1))
print (arr1[4], arr1[-4], arr1[6], arr1[-2], arr1[3], arr1[-5])  # indexing
print (arr1[3:], arr1[-5:])
print (arr1[:4], arr1[:-4])
print (arr1[::2], arr1[1::2], arr1[::-1])

[200 300 500 600 400 900 700 800] <class 'numpy.ndarray'> 8
400 400 700 700 600 600
[600 400 900 700 800] [600 400 900 700 800]
[200 300 500 600] [200 300 500 600]
[200 500 400 700] [300 600 900 800] [800 700 900 400 600 500 300 200]


In [69]:
# Classwork: Print 300 to 900 in 4 different ways
print (arr1[1:6], arr1[-7:-2], arr1[1:-2], arr1[-7:6])

[300 500 600 400 900] [300 500 600 400 900] [300 500 600 400 900] [300 500 600 400 900]


### Views and Copies

In [76]:
arr1 = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
print (arr1, type(arr1), len(arr1))
arr2 = arr1[4:8]
print (arr2, type(arr2), len(arr2))
arr1[4:8] = 999
print (arr1, type(arr1), len(arr1))
print (arr2, type(arr2), len(arr2))

[ 100  200  300  400  500  600  700  800  900 1000] <class 'numpy.ndarray'> 10
[500 600 700 800] <class 'numpy.ndarray'> 4
[ 100  200  300  400  999  999  999  999  900 1000] <class 'numpy.ndarray'> 10
[999 999 999 999] <class 'numpy.ndarray'> 4


In [77]:
arr1 = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])
print (arr1, type(arr1), len(arr1))
arr2 = arr1[4:8].copy()
print (arr2, type(arr2), len(arr2))
arr1[4:8] = 999
print (arr1, type(arr1), len(arr1))
print (arr2, type(arr2), len(arr2))

[ 100  200  300  400  500  600  700  800  900 1000] <class 'numpy.ndarray'> 10
[500 600 700 800] <class 'numpy.ndarray'> 4
[ 100  200  300  400  999  999  999  999  900 1000] <class 'numpy.ndarray'> 10
[500 600 700 800] <class 'numpy.ndarray'> 4


In [79]:
var1 = 200
print (var1, id(var1))
var2 = var1
print (var2, id(var2))
var3 = 200
print (var3, id(var3))

200 140709502402576
200 140709502402576
200 140709502402576


In [81]:
var1 = 257
print (var1, id(var1))
var2 = var1
print (var2, id(var2))
var3 = 257
print (var3, id(var3))

257 1192133844656
257 1192133844656
257 1192133844880


In [83]:
var1 = -6
print (var1, id(var1))
var2 = var1
print (var2, id(var2))
var3 = -6
print (var3, id(var3))
# so as a conclusion variable with values ranging from -5 to 256 will have same ids.

-6 1192127605168
-6 1192127605168
-6 1192127604176
