## Introduction to Pandas: Data Manipulation

> It is often said that 80% of data analysis is spent on the data cleaning and preparing data. To get a handle on the problem, this section will focus on a small but important aspect of data manipulation and cleaning with Pandas.

### Data Structures in Pandas

**There are two different data Structures are there in Pandas -**
* **Series -** It is an one-dimensional labeled array capable of holding any data type data (e.g. integer, list, dictionary, floating point, string, Python objects etc.). The axis are collectively referred to as the index.
* **Data Frame -** It is a two-domensional labeled data structure with columns of potentially different types. You can consider a Data Frame as one SQL Table of MS-Excel Spreadsheet.

### Series Data Structure

**pandas.code,series,Series(data, index, dtype, copy)**
* **data -** data may take various formats
* **index -** it is unique and hashable for easy data access and identification
* **dtype -** it is for data type
* **copy -** copy data, default is False (only affects Series on ndarray data sources)

In [1]:
# importing required modules
import pandas as pd
import numpy as np

In [6]:
# creating a Series from a ndarray
my_data = np.array(['Amit', 'Kamal', "Hari", "Imtiaz"])
print (my_data, type(my_data))
s = pd.Series(data = my_data)
print (s)
print (type(s))
print (s[0], s[3])

['Amit' 'Kamal' 'Hari' 'Imtiaz'] <class 'numpy.ndarray'>
0      Amit
1     Kamal
2      Hari
3    Imtiaz
dtype: object
<class 'pandas.core.series.Series'>
Amit Imtiaz


In [8]:
# creating a Series from a ndarray
my_data = np.array(['Amit', 'Kamal', "Hari", "Imtiaz"])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['Kol', 'Mum', 'Che', 'Del'])
print (s)
print (type(s))
print (s['Mum'], s['Del'])
print (s[0], s[3])

['Amit' 'Kamal' 'Hari' 'Imtiaz'] <class 'numpy.ndarray'>
Kol      Amit
Mum     Kamal
Che      Hari
Del    Imtiaz
dtype: object
<class 'pandas.core.series.Series'>
Kamal Imtiaz
Amit Imtiaz


In [9]:
# creating a Series from a ndarray
my_data = np.array(['Amit', 'Kamal', "Hari", "Imtiaz"])
print (my_data, type(my_data))
s = pd.Series(my_data, index = ['Kol', 'Mum', 'Che', 'Del'])
print (s)
print (type(s))
print (s['Mum'], s['Del'])
print (s[0], s[3])

['Amit' 'Kamal' 'Hari' 'Imtiaz'] <class 'numpy.ndarray'>
Kol      Amit
Mum     Kamal
Che      Hari
Del    Imtiaz
dtype: object
<class 'pandas.core.series.Series'>
Kamal Imtiaz
Amit Imtiaz


In [15]:
# creating a Series from a ndarray
my_data = np.array(['Amit', 'Kamal', "Hari", "Imtiaz", "Prasenjit"])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = ['Kol', 'Mum', 'Kol', 'Mum', 'Del'])
print (s)
print (type(s))
print (s['Mum'])
print (s['Kol'], type(s['Kol']))
print (s['Del'], type(s['Del']))
# print (s[0], s[3])

['Amit' 'Kamal' 'Hari' 'Imtiaz' 'Prasenjit'] <class 'numpy.ndarray'>
Kol         Amit
Mum        Kamal
Kol         Hari
Mum       Imtiaz
Del    Prasenjit
dtype: object
<class 'pandas.core.series.Series'>
Mum     Kamal
Mum    Imtiaz
dtype: object
Kol    Amit
Kol    Hari
dtype: object <class 'pandas.core.series.Series'>
Prasenjit <class 'str'>


In [18]:
# creating a Series from a ndarray
my_data = np.array(['Amit', 'Kamal', "Hari", "Imtiaz", "Prasenjit"])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [101, 102, 103, 104, 105])
print (s)
print (type(s))
print (s[101])
print (s[103])

['Amit' 'Kamal' 'Hari' 'Imtiaz' 'Prasenjit'] <class 'numpy.ndarray'>
101         Amit
102        Kamal
103         Hari
104       Imtiaz
105    Prasenjit
dtype: object
<class 'pandas.core.series.Series'>
Amit
Hari


In [19]:
# creating a Series from a ndarray
my_data = np.array(['Amit', 'Kamal', "Hari", "Imtiaz", "Prasenjit"])
print (my_data, type(my_data))
s = pd.Series(data = my_data, index = [101, 102, 103, 101, 105])
print (s)
print (type(s))
print (s[101])
print (s[103])

['Amit' 'Kamal' 'Hari' 'Imtiaz' 'Prasenjit'] <class 'numpy.ndarray'>
101         Amit
102        Kamal
103         Hari
101       Imtiaz
105    Prasenjit
dtype: object
<class 'pandas.core.series.Series'>
101      Amit
101    Imtiaz
dtype: object
Hari


In [24]:
arr1 = np.array([100, 200, 300, 400, 500])
print (arr1, type(arr1))
s = pd.Series(data = arr1, copy = False)
print (s)
print (type(s))
s[0] = 111
arr1[1] = 222
print (arr1)
print (s)

[100 200 300 400 500] <class 'numpy.ndarray'>
0    100
1    200
2    300
3    400
4    500
dtype: int32
<class 'pandas.core.series.Series'>
[111 222 300 400 500]
0    111
1    222
2    300
3    400
4    500
dtype: int32


In [38]:
arr1 = np.array([100, 200, 300, 400, 500])
print (arr1, type(arr1))
s = pd.Series(data = arr1, copy = True)
print (s)
print (type(s))
s[0] = 111
arr1[1] = 222
print (arr1)
print (s)

[100 200 300 400 500] <class 'numpy.ndarray'>
0    100
1    200
2    300
3    400
4    500
dtype: int32
<class 'pandas.core.series.Series'>
[100 222 300 400 500]
0    111
1    200
2    300
3    400
4    500
dtype: int32


In [29]:
# creating a Series from a dictionary
my_data = {'aa':100, 'bb':300, 'cc':500, 'dd':700}
print (my_data, type(my_data))

s = pd.Series(data = my_data)
print (s)

s = pd.Series(data = my_data, index = ['aa', 'cc', 'cc', 'dd', 'bb', 'xx'])
print (s)

{'aa': 100, 'bb': 300, 'cc': 500, 'dd': 700} <class 'dict'>
aa    100
bb    300
cc    500
dd    700
dtype: int64
aa    100.0
cc    500.0
cc    500.0
dd    700.0
bb    300.0
xx      NaN
dtype: float64


In [34]:
# creating a Series from a scalar or from a constant
s = pd.Series(5, index = [0, 1, 2, 3, 4])
print (s)
print (type(s))
print ()
s = pd.Series(5, range(5))
print (s)
print (type(s))

0    5
1    5
2    5
3    5
4    5
dtype: int64
<class 'pandas.core.series.Series'>

0    5
1    5
2    5
3    5
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [42]:
s = pd.Series(data = ['Kamal', 'Amitava', 'Barun', "Harbhajan"], index = [300, 200, 100, 600])
print (s)
print()
print (s.sort_values())
print ()
print (s.sort_index())

300        Kamal
200      Amitava
100        Barun
600    Harbhajan
dtype: object

200      Amitava
100        Barun
600    Harbhajan
300        Kamal
dtype: object

100        Barun
200      Amitava
300        Kamal
600    Harbhajan
dtype: object


In [46]:
# creating a Series from a list
s = pd.Series([11, 33, 22, 44, 66, 55], index = ['aa', 'bb', 'cc', 'dd', 'ee', 'ff'])
print (s)
print (s[0], s['aa'])  # indexing
print (s[1], s['bb'])
print (s[3:])   # slicing
print (s[:4])

aa    11
bb    33
cc    22
dd    44
ee    66
ff    55
dtype: int64
11 11
33 33
dd    44
ee    66
ff    55
dtype: int64
aa    11
bb    33
cc    22
dd    44
dtype: int64


### Pandas Data Structure

In [55]:
my_data = {'emp_name':['Amal', 'Kamal', 'Bimal', 'Shyamal'], 'emp_age':[34, 54, 23, 22]}
print (my_data, type(my_data))
emp_id = [101, 102, 103, 104]
df = pd.DataFrame(data = my_data)
print (df)
df

{'emp_name': ['Amal', 'Kamal', 'Bimal', 'Shyamal'], 'emp_age': [34, 54, 23, 22]} <class 'dict'>
  emp_name  emp_age
0     Amal       34
1    Kamal       54
2    Bimal       23
3  Shyamal       22


emp_name  emp_age
0     Amal       34
1    Kamal       54
2    Bimal       23
3  Shyamal       22

In [53]:
var1 = 100
var2 = 200
print (var1)
print (var2)
var2

100
200


200

In [65]:
my_data = {'emp_name':['Amal', 'Kamal', 'Bimal', 'Shyamal'], 'emp_age':[34, 54, 23, 22]}
print (my_data, type(my_data))
emp_id = [101, 102, 103, 104]
df = pd.DataFrame(data = my_data, index = emp_id)
df

{'emp_name': ['Amal', 'Kamal', 'Bimal', 'Shyamal'], 'emp_age': [34, 54, 23, 22]} <class 'dict'>


emp_name  emp_age
101     Amal       34
102    Kamal       54
103    Bimal       23
104  Shyamal       22

In [66]:
df.reset_index()

index emp_name  emp_age
0    101     Amal       34
1    102    Kamal       54
2    103    Bimal       23
3    104  Shyamal       22

In [67]:
# df = df.reset_index()
df.reset_index(inplace = True)
df

index emp_name  emp_age
0    101     Amal       34
1    102    Kamal       54
2    103    Bimal       23
3    104  Shyamal       22

### Create Data Frame

In [99]:
my_columns = ['name', 'age', 'gender', 'job']
my_data = [['alice', 19, 'F', 'student'], ['john', 26, 'M', 'student']]
user1 = pd.DataFrame(data = my_data)
user1

0   1  2        3
0  alice  19  F  student
1   john  26  M  student

In [103]:
my_columns = ('name', 'age', 'gender', 'job')
my_data = (('alice', 19, 'F', 'student'), ('john', 26, 'M', 'student'))
user1 = pd.DataFrame(data = my_data, columns = my_columns)
user1

name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [104]:
my_columns = ['name', 'age', 'gender', 'job']
my_data = [['eric', 22, 'M', 'student'], ['paul', 38, 'F', 'manager']]
user2 = pd.DataFrame(data = my_data, columns = my_columns)
user2

name  age gender      job
0  eric   22      M  student
1  paul   38      F  manager

In [121]:
my_data = dict(name = ['peter', 'julie'], age = [33, 44], gender = ['M', 'F'], job = ['engineer','scientist'])
print (my_data, type(my_data))
user3 = pd.DataFrame(data = my_data)
user3

{'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']} <class 'dict'>


name  age gender        job
0  peter   33      M   engineer
1  julie   44      F  scientist

In [122]:
print (user3.name)
print (type(user3.name))
print (np.array(user3.name))
print (type(np.array(user3.name)))

0    peter
1    julie
Name: name, dtype: object
<class 'pandas.core.series.Series'>
['peter' 'julie']
<class 'numpy.ndarray'>


In [123]:
print (user3["name"])
print (type(user3["name"]))
print (np.array(user3["name"]))
print (type(np.array(user3["name"])))

0    peter
1    julie
Name: name, dtype: object
<class 'pandas.core.series.Series'>
['peter' 'julie']
<class 'numpy.ndarray'>


In [124]:
user3[['job', 'name']]

job   name
0   engineer  peter
1  scientist  julie

In [125]:
X = user3[['job', 'name']].to_numpy()
print (X)
print (type(X))

[['engineer' 'peter']
 ['scientist' 'julie']]
<class 'numpy.ndarray'>


### Concatenate Data Frame

In [126]:
user1.append(user2)

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
0   eric   22      M  student
1   paul   38      F  manager

In [127]:
user1.append(user2, ignore_index = True)

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student
3   paul   38      F  manager

In [128]:
user1.append(user2).append(user3, ignore_index = True)

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   38      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [130]:
users = pd.concat([user1, user2, user3], ignore_index = True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   38      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

### Join Data Frame

In [131]:
my_dict = dict(name = ['alice', 'john', 'eric', 'julie', 'michel'],
               height = [170, 160, 165, 155, 140])
user4 = pd.DataFrame(data = my_dict)
user4

name  height
0   alice     170
1    john     160
2    eric     165
3   julie     155
4  michel     140

In [133]:
# inner join: only common rows from both tables
merge_inner = pd.merge(users, user4, on = "name", how = "inner")
merge_inner

name  age gender        job  height
0  alice   19      F    student     170
1   john   26      M    student     160
2   eric   22      M    student     165
3  julie   44      F  scientist     155

In [134]:
# inner join: only common rows from both tables
merge_inner = pd.merge(users, user4, on = "name")  # by default inner join
merge_inner

name  age gender        job  height
0  alice   19      F    student     170
1   john   26      M    student     160
2   eric   22      M    student     165
3  julie   44      F  scientist     155

In [135]:
# outer join: all rows from both tables
merge_outer = pd.merge(users, user4, on = "name", how = "outer")
merge_outer

name   age gender        job  height
0   alice  19.0      F    student   170.0
1    john  26.0      M    student   160.0
2    eric  22.0      M    student   165.0
3    paul  38.0      F    manager     NaN
4   peter  33.0      M   engineer     NaN
5   julie  44.0      F  scientist   155.0
6  michel   NaN    NaN        NaN   140.0

In [136]:
# left join: all rows from the left and matching rows from the right
merge_left = pd.merge(users, user4, on = "name", how = "left")
merge_left

name  age gender        job  height
0  alice   19      F    student   170.0
1   john   26      M    student   160.0
2   eric   22      M    student   165.0
3   paul   38      F    manager     NaN
4  peter   33      M   engineer     NaN
5  julie   44      F  scientist   155.0

In [137]:
# right join: mathcing rows from the left and all rows from the right
merge_right = pd.merge(users, user4, on = "name", how = "right")
merge_right

name   age gender        job  height
0   alice  19.0      F    student     170
1    john  26.0      M    student     160
2    eric  22.0      M    student     165
3   julie  44.0      F  scientist     155
4  michel   NaN    NaN        NaN     140

### Summarize

In [140]:
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   38      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [148]:
merge_outer

name   age gender        job  height
0   alice  19.0      F    student   170.0
1    john  26.0      M    student   160.0
2    eric  22.0      M    student   165.0
3    paul  38.0      F    manager     NaN
4   peter  33.0      M   engineer     NaN
5   julie  44.0      F  scientist   155.0
6  michel   NaN    NaN        NaN   140.0

In [151]:
print (users.shape, "#rows =", users.shape[0], "and #cols =", users.shape[1])
print (users.size, merge_outer.size)
print (users.dtypes)
print (users.values, type(users.values), users.values.shape)
print (users.index)
print (users.columns)
print (len(users))

(6, 4) #rows = 6 and #cols = 4
24 35
name      object
age        int64
gender    object
job       object
dtype: object
[['alice' 19 'F' 'student']
 ['john' 26 'M' 'student']
 ['eric' 22 'M' 'student']
 ['paul' 38 'F' 'manager']
 ['peter' 33 'M' 'engineer']
 ['julie' 44 'F' 'scientist']] <class 'numpy.ndarray'> (6, 4)
RangeIndex(start=0, stop=6, step=1)
Index(['name', 'age', 'gender', 'job'], dtype='object')
6


In [152]:
users.describe()

age
count   6.000000
mean   30.333333
std     9.688481
min    19.000000
25%    23.000000
50%    29.500000
75%    36.750000
max    44.000000

In [153]:
users.describe(include='all')

name        age gender      job
count      6   6.000000      6        6
unique     6        NaN      2        4
top     eric        NaN      M  student
freq       1        NaN      3        3
mean     NaN  30.333333    NaN      NaN
std      NaN   9.688481    NaN      NaN
min      NaN  19.000000    NaN      NaN
25%      NaN  23.000000    NaN      NaN
50%      NaN  29.500000    NaN      NaN
75%      NaN  36.750000    NaN      NaN
max      NaN  44.000000    NaN      NaN

In [154]:
users.describe(include = ['object'])

name gender      job
count      6      6        6
unique     6      2        4
top     eric      M  student
freq       1      3        3

In [156]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    6 non-null      object
 1   age     6 non-null      int64 
 2   gender  6 non-null      object
 3   job     6 non-null      object
dtypes: int64(1), object(3)
memory usage: 320.0+ bytes


### Column Selection

In [157]:
users.age

0    19
1    26
2    22
3    38
4    33
5    44
Name: age, dtype: int64

In [158]:
users['age']

0    19
1    26
2    22
3    38
4    33
5    44
Name: age, dtype: int64

In [159]:
users[['age', 'name']]

age   name
0   19  alice
1   26   john
2   22   eric
3   38   paul
4   33  peter
5   44  julie

### Rows Selection

In [161]:
df = users.copy()
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   38      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [164]:
print (df.iloc[0])
print ()
print (df.loc[0])

name        alice
age            19
gender          F
job       student
Name: 0, dtype: object

name        alice
age            19
gender          F
job       student
Name: 0, dtype: object


In [165]:
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   38      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [173]:
print (df.iloc[4][3], df.iloc[4]['job'], df.loc[4][3], df.loc[4]['job'])
print (df.iloc[4, 3], df.iloc[4]['job'], df.loc[4][3], df.loc[4, 'job'])

engineer engineer engineer engineer
engineer engineer engineer engineer


In [179]:
df = users.copy()
for i in range(df.shape[0]):
    row = df.iloc[i]
    # print (row.age)
    row.age += 100
    # print(row.age)
    df.iloc[i] = row
df

name  age gender        job
0  alice  119      F    student
1   john  126      M    student
2   eric  122      M    student
3   paul  138      F    manager
4  peter  133      M   engineer
5  julie  144      F  scientist

### Rows Selection and Filtering

In [180]:
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   38      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [181]:
users.age > 30

0    False
1    False
2    False
3     True
4     True
5     True
Name: age, dtype: bool

In [182]:
users[users.age > 30]

name  age gender        job
3   paul   38      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [183]:
users[(users.age > 30) & (users.gender == 'F')]

name  age gender        job
3   paul   38      F    manager
5  julie   44      F  scientist

In [184]:
users[(users.age > 30) & (users.gender == 'F')][['name', 'gender']]

name gender
3   paul      F
5  julie      F

In [188]:
users[users.job.isin(['student', 'manager'])]

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student
3   paul   38      F  manager